WebApplication3/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            return View( );
        }


        private readonly TableContext _context;

        public ShopController(TableContext context)
        {
            _context = context;
        }

      

       // [HttpGet] 
        public async Task<ActionResult<IEnumerable<Product>>> GetProducts()
        {
            return View(await _context.Products.ToListAsync());
        }

    }
}

WebApplication3/SmallCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Models;


namespace WebApplication3
{
	public class SmallCartViewComponent : ViewComponent
	{

		public IViewComponentResult Invoke()
			{
			List<CartItem> cart = HttpContext.Session.GetJson<List<CartItem>>("Cart");
			SmallCartViewModel smallCartVM;

			if(cart==null || cart.Count==0)
			{
				smallCartVM = null;
			}
			else
			{
				smallCartVM = new()
				{
					number_of_items = cart.Sum(x => x.quantity),
					total_amount = (int)cart.Sum(x => x.quantity * x.price)
				};
			}

			return View(smallCartVM);
			}
	}
}

WebApplication3/Views/Shop/GetProducts.cshtml
@model IEnumerable<WebApplication3.Models.Product>

@{
    ViewData["Title"] = "GetProducts";
}




</div>
<!DOCTYPE html>
<html>
<head>
	<title>Grocery Store a Ecommerce Online Shopping Category Flat Bootstrap Responsive Website Template | Fruits & Vegetables :: w3layouts</title>
	<!-- for-mobile-apps -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Grocery Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script type="application/x-javascript">
		addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
			   function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- //for-mobile-apps -->
	<link href=" ~/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<!-- font-awesome icons -->
	<link href="~/css/font-awesome.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //font-awesome icons -->
	<!-- js -->
	<script src="~/js/jquery-1.11.1.min.js"></script>
	<!-- //js -->
	<link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
	<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
	<!-- start-smoth-scrolling -->
	<script type="text/javascript" src="~/js/move-top.js"></script>
	<script type="text/javascript" src="~/js/easing.js"></script>
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
			});
		});
	</script>
	<!-- start-smoth-scrolling -->

	<title>W3.CSS</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta content="text/html; charset=iso-8859-2" http-equiv="Content-Type">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<style>
		.mySlides {
			display: none;
		}
	</style>

</head>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
	var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
	(function () {
		var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
		s1.async = true;
		s1.src = 'https://embed.tawk.to/6446514931ebfa0fe7fa0a61/1gupar2gd';
		s1.charset = 'UTF-8';
		s1.setAttribute('crossorigin', '*');
		s0.parentNode.insertBefore(s1, s0);
	})();
</script>
<!--End of Tawk.to Script-->
<body>





	<!-- header -->
	<div class="agileits_header">
		<div class="w3l_offers">
			<a href="products.html">Today's special Offers !</a>
		</div>
		<div class="w3l_search">
			<form action="#" method="post">
				<input type="text" name="Product" value="Search a product..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search a product...';}" required="">
				<input type="submit" value=" ">
			</form>
		</div>
		
		<div class="w3l_header_right">
			<ul>
				<li class="dropdown profile_details_drop">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i><span class="caret"></span></a>
					<div class="mega-dropdown-menu">
						<div class="w3ls_vegetables">
							<ul class="dropdown-menu drp-mnu">
								<li><a href="login.html">Login</a></li>
								<li><a href="login.html">Sign Up</a></li>
							</ul>
						</div>
					</div>
				</li>
			</ul>
		</div>
		<div class="w3l_header_right1">
			<h2><a href="mail.html">Contact Us</a></h2>
		</div>
		<div class="clearfix"> </div>
	</div>
	<!-- script-for sticky-nav -->
	<script>
		$(document).ready(function () {
			var navoffeset = $(".agileits_header").offset().top;
			$(window).scroll(function () {
				var scrollpos = $(window).scrollTop();
				if (scrollpos >= navoffeset) {
					$(".agileits_header").addClass("fixed");
				} else {
					$(".agileits_header").removeClass("fixed");
				}
			});

		});
	</script>
	<!-- //script-for sticky-nav -->
	<div class="logo_products">
		<div class="container">
			<div class="w3ls_logo_products_left">
				<h1><a href="index.html"><span>Car Spare Parts</span> Store</a></h1>
			</div>
			<div class="w3ls_logo_products_left1">
				<ul class="special_items">
					
					<li><a href="about.html">About Us</a><i>/</i></li>
					
					<li><a href="services.html">Services</a></li>
				</ul>
			</div>
			<div class="w3ls_logo_products_left1">
				<ul class="phone_email">
					<li><i class="fa fa-phone" aria-hidden="true"></i>(+0123) 234 567</li>
					<li><i class="fa fa-envelope-o" aria-hidden="true"></i><a href="mailto:store@carparts.com">store@carparts.com</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!-- //header -->

	<div class="container">
		<main role="main" class="pb-3">
			<div class="row">
				<div class="bg-success mt-3 p-3 text-white">
					<vc:small-cart />
				</div>

			</div>
		</main>


		<h2 class="w3-center">Spare Parts</h2>

		<div class="w3-content w3-section" style="max-width:500px">
			<img class="mySlides" src="~/images/car1.jpg" style="width:100%">
			<img class="mySlides" src="~/images/car2.jpg" style="width:100%">
			<img class="mySlides" src="~/images/car3.jpg" style="width:100%">
			<img class="mySlides" src="~/images/car4.jpg" style="width:100%">
		</div>

		<script>
			var myIndex = 0;
			carousel();

			function carousel() {
				var i;
				var x = document.getElementsByClassName("mySlides");
				for (i = 0; i < x.length; i++) {
					x[i].style.display = "none";
				}
				myIndex++;
				if (myIndex > x.length) { myIndex = 1 }
				x[myIndex - 1].style.display = "block";
				setTimeout(carousel, 2000); // Change image every 2 seconds
			}
		</script>
<div class="w3ls_w3l_banner_nav_right_grid w3ls_w3l_banner_nav_right_grid_veg">
	<h3 class="w3l_fruit">PRODUCTS</h3>
	@foreach (var x in Model)
	{
		<div class="w3ls_w3l_banner_nav_right_grid1 w3ls_w3l_banner_nav_right_grid1_veg">
			<div class="col-md-10 w3ls_w3l_banner_left w3ls_w3l_banner_left_asdfdfd">
				<div class="hover14 column">
					<div class="agile_top_brand_left_grid w3l_agile_top_brand_left_grid">
								<div class="tag"><img src="~/images/o-13.png" alt=" " class="img-responsive"></div>
							<div class="agile_top_brand_left_grid1">

							<figure>

								<div class="snipcart-item block">
									<div class="snipcart-thumb">
										<div class="col-80">
											<h2>@x.product_name</h2>
											<p>Car Model:@x.car_model</p>
											<p>Stock:@x.stock</p>
											<hidden>Product No:@x.product_id</hidden>

											<h4>@x.price.ToString("C2") TL</h4>

											<p>
												<a class="btn btn-primary" asp-controller="Cart" asp-action="Add" asp-route-id="@x.product_id">Add to cart</a>
											</p>
											

										</div>

									</div>

								</div>
							</figure>

						</div>
					</div>
				</div>
			</div>


		</div>
	}
</div>

	<div class="newsletter">
		<div class="container">
			<div class="w3agile_newsletter_left">
				<h3>sign up for our newsletter</h3>
			</div>
			<div class="w3agile_newsletter_right">
				<form action="#" method="post">
					<input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
					<input type="submit" value="subscribe now">
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>

	<!-- footer -->
	<div class="footer">
		<div class="container">
			<div class="col-md-3 w3_footer_grid">
				<h3>information</h3>
				<ul class="w3_footer_grid_list">
					<li><a href="events.html">Events</a></li>
					<li><a href="about.html">About Us</a></li>
					<li><a href="products.html">Best Deals</a></li>
					<li><a href="services.html">Services</a></li>
					<li><a href="short-codes.html">Short Codes</a></li>
				</ul>
			</div>

			<div class="col-md-3 w3_footer_grid">
				<h3>what in stores</h3>
				<ul class="w3_footer_grid_list">
					<li>Car Spare Parts</li>
				</ul>
			</div>
		
			<div class="clearfix"> </div>
			<div class="agile_footer_grids">
				<div class="col-md-3 w3_footer_grid agile_footer_grids_w3_footer">
					<div class="w3_footer_grid_bottom">
						<h4>100% secure payments</h4>
						
					</div>
				</div>
				<div class="col-md-3 w3_footer_grid agile_footer_grids_w3_footer">
					<div class="w3_footer_grid_bottom">
						<h5>connect with us</h5>
						<ul class="agileits_social_icons">
							<li><a href="#" class="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
							<li><a href="#" class="twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							<li><a href="#" class="google"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
							<li><a href="#" class="instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
							<li><a href="#" class="dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="wthree_footer_copy">
				<p>© 2023 Car Parts Store. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
			</div>
		</div>
	</div>
	<!-- //footer -->

</body>

</html>

@*@foreach (var x in Model)
{
	<div class="col-4">
	<h2>@x.product_name</h2>
	<p>Stock:@x.stock</p>
	<p>@x.product_id</p>
	<p>@x.car_model</p>
	<h4>@x.price.ToString("C2") TL</h4>

	<p> 
		<a class="btn btn-primary" asp-controller="Cart" asp-action="Add" asp-route-id="@x.product_id">Add to cart</a>
    </p>
		<div> <vc:small-cart /></div>
	
		</div>

}*@

WebApplication3/Views/Shop/Payment.cshtml
@using WebApplication3.Models
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="place-order">
    <h4>Your Order</h4>
    <div class="order-total">
        <ul class="order-table">
            
            <li>Product<span>Total</span></li>
           @* @foreach(var item in (List<CartItem>)Session["Cart"])
            {
                
            }*@
            <li class="fw-normal"><span></span></li>
            <li class="total-price">Total<span>  </span> </li>
        </ul>
    </div>

</div>